on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bulid:
    runs-on: macos-13.5
    steps: 
     - name: Checkout
       uses: actions/checkout@v3
     - name: xcodeBuild
       uses: mxcl/xcodebuild@v2.0.0
       with:
         scheme: BoldlyGiffingiOS
         xcode: ^14.3
         platform: iOS
